version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: codeanding-food
    restart: always
    environment:
      POSTGRES_USER: codeanding-dev
      POSTGRES_PASSWORD: codeanding-pwd
      POSTGRES_DB: food
    ports:
      - '54321:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
